define(function() {
    return {
        "properties": [{
            "name": "rememberMeSelectedSource",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "logoSource",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "rememberMeUnSelectedSource",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "logoScaleMode",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "usernamePlaceholder",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "passwordPlaceholder",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "usernameMaxChar",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "passwordMaxChar",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "usernameInputMode",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "passwordInputMode",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "remembermeProperty",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "socialLoginVisible",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "forgotPasswordText",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "submitButtonText",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "touchIdCenterY",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "socialLoginCenterY",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "facebookLogin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "facebookCenterX",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "linkedinLogin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "linkedinCenterX",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "office365Login",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "office365CenterX",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "facebookSource",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "linkedinSource",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "office365Source",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "usernameMinimumChar",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "passwordMinimumChar",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "usernameValidationMsg",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "passwordValidationMsg",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "providerName",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "encryptCredentials",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "faceIdProperty",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "touchIDProperty",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }],
        "apis": ["invokeIdentityService", "getUsername", "getPassword", "enableTouchID", "rememberMe"],
        "events": ["forgotPasswordOnClick", "loginSuccessEvent", "usernameOnDone", "passwordOnDone", "submitOnClick", "remembermeOnSelection", "loginFailureEvent"]
    }
});