define(function() {
    return {
        "properties": [{
            "name": "btnSignInSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "btnText",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "enrollTimeout",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "verifyTimeout",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "licenseString",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "tokenName",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "enrollQualityThreshold",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "livenessMode",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "serverURL",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "tokenConfigType",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "livenessThreshold",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "blinkTimeout",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "secret",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "verifyQualityThreshold",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "pin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "matchingThreshold",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }],
        "apis": ["configuration", "initialize", "enroll", "verify", "unenroll", "uninitialize"],
        "events": ["onEnrollSuccess", "onInitSuccess", "onVerifySuccess", "onUnenrollSuccess", "onInitFailure", "onVerifyFailure", "onEnrollFailure", "onUnenrollFailure"]
    }
});